### ISSUE TITLE
suggestion: use 24-hour clock instead of AM/PM

### ISSUE THREAD

**Issue by NicolasSchmutz** [renee-bar/renee-bar.github.io#33]
>Fr, 9 Sep 12am
First Anniversary Celebration: Neevo. Cosmic-danc, tropical-rock, afro-disco
Su, 11 Sep 12am
First Anniversary Celebration: DJ OMG Luc, Mach Schnell, Brl. Spicy bubblegum, garage, r'n'r

Events that start at midnight are displayed as 12am which this is rather confusing and not correct: https://www.quora.com/Is-12-00-at-midday-12pm-or-12am

😬✌🏽

**Comment by njam** [comment]
The Quora post you linked is about mid*day*, but the examples are for mid*night*. When using the am/pm notation then "12am" seems to be what's commonly used.

But I agree that am/pm notation might not be the best idea, since most website visitors will be used to the 24h format.
@patrickwermelinger wdyt?

**Comment by njam** [comment]
Overview from Wikipedia:
![image](https://cloud.githubusercontent.com/assets/360800/18417193/5a22f400-7829-11e6-9299-05eb95be94c8.png)
https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight
